# Generated by Django 4.0.5 on 2022-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_r', '0002_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
