# Generated by Django 4.0.5 on 2022-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_r', '0003_alter_rate_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='projects'),
        ),
    ]
